# Configuration for updating dependencies.
#
# Check for updates to
# - ICU
# - ccache for Windows
# - Python for Windows
# - Python for macOS universal
# - Cython
# - manylinux
#
# For each dependency that has an update, we create a pull request containing a
# single commit that updates the dependency.

name: Dependency Update

on:
  workflow_dispatch:
    inputs:
      BUILD_PULL_REQUEST:
        type: boolean
        description: Build pull requests created by this workflow
        default: true

jobs:
  autoupdate-ICU:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_icu.py ${{ secrets.GITHUB_TOKEN }}
      - name: allow building pull requests
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 'true'
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST == 'false'
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        uses: peter-evans/create-pull-request@v6
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-ICU] update ICU from \"${{ env.ICU_NAME_OLD }}\" to \"${{ env.ICU_NAME_LATEST }}\""
          branch: autoupdate-ICU
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update ICU from \"${{ env.ICU_NAME_OLD }}\" to \"${{ env.ICU_NAME_LATEST }}\""
          body: |-
            As of ${{ env.ICU_PUBLISHED_AT }}, a new version of ICU has been released.

            Release Information (sourced from ${{ env.ICU_HTML_URL }})
            <blockquote>

            ${{ env.ICU_RELEASE_INFO }}
            </blockquote>

            *I am a bot, and this action was performed automatically.*

  autoupdate-JSON:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_json.py ${{ secrets.GITHUB_TOKEN }}
      - name: allow building pull requests
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 'true'
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST == 'false'
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        uses: peter-evans/create-pull-request@v6
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-JSON] update JSON for Modern C++ from \"${{ env.JSON_VERSION_OLD }}\" to \"${{ env.JSON_VERSION_LATEST }}\""
          branch: autoupdate-JSON
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update JSON for Modern C++ from \"${{ env.JSON_VERSION_OLD }}\" to \"${{ env.JSON_VERSION_LATEST }}\""
          body: |-
            As of ${{ env.JSON_PUBLISHED_AT }}, a new version of JSON for Modern C++ has been released.

            Release Information (sourced from ${{ env.JSON_HTML_URL }})
            <blockquote>

            ${{ env.JSON_RELEASE_INFO }}
            </blockquote>

            *I am a bot, and this action was performed automatically.*

  autoupdate-ccache:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: install Python packages
        run: pip3 install --user beautifulsoup4
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_ccache.py ${{ secrets.GITHUB_TOKEN }}
      - name: allow building pull requests
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 'true'
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST == 'false'
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        uses: peter-evans/create-pull-request@v6
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-ccache] update ccache from ${{ env.CCACHE_VERSION_OLD }} to ${{ env.CCACHE_VERSION }}"
          branch: autoupdate-ccache
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update ccache from ${{ env.CCACHE_VERSION_OLD }} to ${{ env.CCACHE_VERSION }}"
          body: |-
            As of ${{ env.CCACHE_PUBLISHED_AT }}, a new version of ccache for Windows has been released.

            Changelog (sourced from ${{ env.CCACHE_CHANGELOG_URL }})
            <blockquote>

            ${{ env.CCACHE_CHANGELOG }}
            </blockquote>

            *I am a bot, and this action was performed automatically.*

  autoupdate-cython:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: install Python packages
        run: pip3 install --user requests beautifulsoup4
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_cython.py
      - name: allow building pull requests
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 'true'
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST == 'false'
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        uses: peter-evans/create-pull-request@v6
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-cython] update Cython from ${{ env.CYTHON_VERSION_OLD }} to ${{ env.CYTHON_VERSION_LATEST }}"
          branch: autoupdate-cython
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update Cython from ${{ env.CYTHON_VERSION_OLD }} to ${{ env.CYTHON_VERSION_LATEST }}"
          body: |-
            A new version of Cython is available.

            Changelog (sourced from https://cython.readthedocs.io/en/latest/src/changes.html)
            <blockquote>

            ${{ env.CYTHON_CHANGELOG }}
            </blockquote>

            *I am a bot, and this action was performed automatically.*

  autoupdate-python-windows:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_python.py win64
      - name: allow building pull requests
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 'true'
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST == 'false'
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        uses: peter-evans/create-pull-request@v6
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-python-windows] update Python for Windows: ${{ env.PYTHON_UPDATE_INFO_ONELINE }}"
          branch: autoupdate-python-windows
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update Python for Windows: ${{ env.PYTHON_UPDATE_INFO_ONELINE }}"
          body: |-
            A new version of Python for Windows is available.

            ${{ env.PYTHON_UPDATE_INFO_MULTILINE }}

            For details of all Python releases, see https://www.nuget.org/packages/python.

            *I am a bot, and this action was performed automatically.*

  autoupdate-python-macosuniversal:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: search for update
        run: |
          pip3 install beautifulsoup4
          $GITHUB_WORKSPACE/actions/update_python.py macos
      - name: allow building pull requests
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 'true'
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST == 'false'
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        uses: peter-evans/create-pull-request@v6
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-python-macosuniversal] update Python for macOS universal: ${{ env.PYTHON_UPDATE_INFO_ONELINE }}"
          branch: autoupdate-python-macosuniversal
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update Python for macOS universal: ${{ env.PYTHON_UPDATE_INFO_ONELINE }}"
          body: |-
            A new version of Python for macOS universal is available.

            ${{ env.PYTHON_UPDATE_INFO_MULTILINE }}

            For details of all Python releases, see https://www.python.org/downloads/macos/.

            *I am a bot, and this action was performed automatically.*

  autoupdate-manylinux:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: install Python packages
        run: pip3 install --user requests
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_manylinux.py
      - name: allow building pull requests
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 'true'
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST == 'false'
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        uses: peter-evans/create-pull-request@v6
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-manylinux] update manylinux: ${{ env.MANYLINUX_UPDATE_INFO_ONELINE }}"
          branch: autoupdate-manylinux
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update manylinux: ${{ env.MANYLINUX_UPDATE_INFO_ONELINE }}"
          body: |-
            A new manylinux image is available.

            ${{ env.MANYLINUX_UPDATE_INFO_MULTILINE }}

            For details regarding manylinux images, see https://github.com/pypa/manylinux.

            *I am a bot, and this action was performed automatically.*
